name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  lintTest: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies..."
          yarn install
      - name: Run Linting
        run: |
          echo "Run Linting Test..."
          yarn lint
        env: 
          CI: true
  
  deploy: 
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lintTest]
    steps:
      - name: Install Dependencies
        run: |
          echo "Deployment in Progress..."
